### PR TITLE
export type MacroContext

### PR DESCRIPTION
**Pull request by ambar**

### CODE REVIEW

**Comment by mischnic** [comment]
This should be available already as `import type {MacroContext} from "@parcel/macros";`

The source for that is here: https://github.com/parcel-bundler/parcel/blob/v2/packages/utils/macros/macros.d.ts

**Comment by ambar** [comment]
That's is impossible, `@parcel/macros` is not in the dependencies:
```bash
➜  git:(main) ✗ npm ls @parcel/macros
└── (empty)
```

**Comment by mischnic** [comment]
Then just add it as an additional dependency. (That package only exports types)
The examples on https://parceljs.org/features/macros/ also use it

**Comment by ambar** [comment]
The API is not the same, maybe we can try pick and re-exporting it.

**Pull request closed without merging**
